### ISSUE TITLE
Spoligotype identification in Mycobacterium spp. samples

### ISSUE THREAD

**Issue by marco315176** [USDA-VS/vSNP3#11]
Hello.
I am interested in analyzing mycobacterial samples for spoligotyping. 
I would like to know how I can generate a database that is useful for this purpose.
Thank you very much in advance.

**Comment by stuber** [comment]
Hi,
I would need to know more about the goals of the project. Please feel free to contact me at tod.p.stuber@usda.gov, and we can discuss it in more detail.
Thanks,

**Comment by marco315176** [comment]
@stuber Thank you very much.
I sent you an email
